# To keep things simple, we're using a whitelist approach
# Add Cops gradually as needed
AllCops:
  DisabledByDefault: true
  Exclude:
    -  db/schema.rb

Style/HashSyntax:
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#hash-literals
  EnforcedStyle: ruby19

Layout/EmptyLines:
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#two-or-more-empty-lines
  Enabled: true

Layout/EmptyLineBetweenDefs:
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#empty-lines-between-methods
  Enabled: true

Layout/EmptyLinesAroundAccessModifier:
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#empty-lines-around-access-modifier
  Enabled: true

Layout/EmptyLinesAroundBeginBody:
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#empty-lines-around-bodies
  Enabled: true

Layout/EmptyLinesAroundBlockBody:
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#empty-lines-around-bodies
  Enabled: true

Layout/EmptyLinesAroundClassBody:
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#empty-lines-around-bodies
  Enabled: true

Layout/EmptyLinesAroundExceptionHandlingKeywords:
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#empty-lines-around-bodies
  Enabled: true

Layout/EmptyLinesAroundMethodBody:
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#empty-lines-around-bodies
  Enabled: true

Layout/EmptyLinesAroundModuleBody:
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#empty-lines-around-bodies
  Enabled: true

Style/RedundantReturn:
  Enabled: true
