language: ruby
dist: focal

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y tidy
  - gem install bundler:1.17.3

before_script:
  # TODO: Reinstate brakeman as soon as we've upgrade to rails 5.2
  # - bundle exec brakeman -z
  - cp config/secrets.yml.example config/secrets.yml
  - cp config/database.travis.yml config/database.yml
  - bundle exec rake db:setup

after_script:
  # See https://github.com/codeclimate/ruby-test-reporter/blob/master/CHANGELOG.md#v100-2016-11-03
  - bundle exec codeclimate-test-reporter

services:
  - mysql
